🚧 Script to strip licenses
This strips some non-license comments, but I'll manually add those back

diff --git a/license-update b/license-update
--- a/license-update
+++ b/license-update
@@ -1,26 +1,17 @@
 #!/bin/bash
 
-license=$(sed -e 's|^#*|// |' <LICENSE)
-
-function _process() {
-  if [ ! -f "$FILE" ]; then
-    return 0
+function updo() {
+  if git check-ignore -q "$1"; then
+    exit
   fi
-  first_line=$(head -n1 <$1)
-  if ! [[ "${first_line}" == //* ]]; then
-    contents="$(<$1)"
-    fixed="${license}
 
-
-${contents}
-"
-    printf "%s" "${fixed}" >"$1"
-    git add -u "$1"
+  (./strip-license.py <"$1" >"$1.tmp") || (echo "Unable to update snippets for $1" && exit 1)
+  if diff -q "$1.tmp" "$1" >/dev/null; then
+    rm "$1.tmp" || (echo "Unable to remove temp file" && exit 1)
+  else
+    mv "$1.tmp" "$1" && git add "$1" || (echo "Unable to copy content" && exit 1)
   fi
 }
 
-if [[ "$1" == --staged ]]; then
-  git diff --staged --name-only | grep '.js$' | while read file; do _process "${file}"; done
-else
-  find src -name '*.js' | while read file; do _process "${file}"; done
-fi
+export -f updo
+find src/ -name \*.js -exec bash -c 'updo "$0"' {} \; || (echo "find failed" && exit 1)
